# Generated by Django 4.2.20 on 2025-04-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready_for_pickup', 'Ready for Pickup'), ('on_delivery', 'On Delivery'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
    ]
