# Generated by Django 5.2 on 2025-04-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
