# Generated by Django 4.2.20 on 2025-04-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_rating_alter_article_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('salads', 'Salads'), ('appetizers', 'Appetizers'), ('main_course', 'Main Course'), ('desserts', 'Desserts')], default='main_course', max_length=20),
        ),
    ]
