# Generated by Django 4.2.20 on 2025-04-30 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='daily_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_reset',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
