# Generated by Django 5.2 on 2026-02-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_daily_earnings_supplier_last_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(blank=True, choices=[('car', 'Кола'), ('motorcycle', 'Мотор'), ('bicycle', 'Велосипед'), ('other', 'Друг')], max_length=20, null=True),
        ),
    ]
