# Generated by Django 5.2 on 2026-02-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplier_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='status',
        ),
    ]
