# Generated by Django 5.2 on 2026-03-05 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_remove_supplier_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='last_reset',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 5, 20, 36, 5, 409603, tzinfo=datetime.timezone.utc)),
        ),
    ]
